### ISSUE TITLE
Launching does not seem to start ext-rust.exe and manual launch no ping response

### ISSUE THREAD

**Issue by AddictArts** [hschneider/neutralino-ext-rust#1]
I was able to build the rust exe. Running `neu run` and clicking ping, there is no response.

Checking the process list there is no ext-rust.exe running. Manual run of ext-rust.exe does not change the ping response either.

Thanks for any help and thanks for the example project.

**Comment by hschneider** [comment]
Thanks for the feedback. Hangon, I'll look into it.

**Comment by hschneider** [comment]
Replace this in the `neutralino.config.json`:
```json
"extensions": [
    {
      "id": "extRust",
      "commandDarwin": "${NL_PATH}/extensions/rust/target/release/ext-rust ${NL_PATH}",
      "commandLinux": "${NL_PATH}/extensions/rust/target/release/ext-rust ${NL_PATH}",
      "commandWindows": "${NL_PATH}\\extensions\\rust\\target\\release\\ext-rust.exe ${NL_PATH}"
    }
  ],
  ```

**Comment by AddictArts** [comment]
Thanks that resolved the issue for the rust example. However, the node is not working using the same method and following the install.cmd etc. Thanks again
